version: '3'
services:

  nginx:
    restart: always
    build: ./nginx
    ports:
      - 80:80
      - 443:443
    depends_on:
      - web
    networks:
      - network
    volumes:
      - ./nginx/certificate:/etc/letsencrypt/live/retail.bnpi.dev
    
  db:
    image: postgres:16
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
    volumes:
      - ./odoo/data/postgres:/var/lib/postgresql/data
    restart: always
    networks:
      - network

  web:
    image: odoo:16
    container_name: odoo-web
    depends_on:
      - db
    ports:
      - "8069:8069"
    volumes:
      - ./odoo/data/odoo-data:/var/lib/odoo
      - ./odoo/config:/etc/odoo:rw
      - ./odoo/addons:/mnt/extra-addons:rw
    tty: true
    command: -- --dev=reload
    restart: always
    networks:
      - network

networks:
  network:

