version: '3'
services:
  db:
    image: postgres:16
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    restart: always
  web:
    image: odoo:16
    container_name: odoo-web
    depends_on:
      - db
    ports:
      - "8070:8069"
    volumes:
      - ./data/odoo-data:/var/lib/odoo
      - ./config:/etc/odoo:rw
      - ./addons:/mnt/extra-addons:rw
    tty: true
    command: -- --dev=reload
    restart: always
